### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by fxt960803** [Sharpiless/yolox-deepsort#2]
(pytorch1.8) D:\yolox-deepsort-main\yolox-deepsort-main>python demo.py
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from AIDetector_pytorch import Detector
  File "D:\yolox-deepsort-main\yolox-deepsort-main\AIDetector_pytorch.py", line 6, in <module>
    from BaseDetector import baseDet
  File "D:\yolox-deepsort-main\yolox-deepsort-main\BaseDetector.py", line 1, in <module>
    from tracker import update_tracker
  File "D:\yolox-deepsort-main\yolox-deepsort-main\tracker.py", line 8, in <module>
    cfg.merge_from_file("deep_sort/configs/deep_sort.yaml")
  File "D:\yolox-deepsort-main\yolox-deepsort-main\deep_sort\utils\parser.py", line 23, in merge_from_file
    self.update(yaml.load(fo.read()))
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by AydinAlptug** [comment]
Did you solved it? @fxt960803

**Comment by y000k** [comment]
pyyaml版本太高，
File "D:\yolox-deepsort-main\yolox-deepsort-main\deep_sort\utils\parser.py", line 23, in merge_from_file
self.update(yaml.load(fo.read()))
改成 self.update(yaml.safe_load(fo.read()))
