### ISSUE TITLE
No such file or directory: 'deep_sort/deep_sort/deep/checkpoint/ckpt.t7'

### ISSUE THREAD

**Issue by EchoYGemini** [Sharpiless/yolox-deepsort#7]
Traceback (most recent call last):
  File "D:/pythonProject3/yolox-deepsort-main/demo.py", line 1, in <module>
    from AIDetector_pytorch import Detector
  File "D:\pythonProject3\yolox-deepsort-main\AIDetector_pytorch.py", line 6, in <module>
    from BaseDetector import baseDet
  File "D:\pythonProject3\yolox-deepsort-main\BaseDetector.py", line 1, in <module>
    from tracker import update_tracker
  File "D:\pythonProject3\yolox-deepsort-main\tracker.py", line 9, in <module>
    deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
  File "D:\pythonProject3\yolox-deepsort-main\deep_sort\deep_sort\deep_sort.py", line 19, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "D:\pythonProject3\yolox-deepsort-main\deep_sort\deep_sort\deep\feature_extractor.py", line 13, in __init__
    state_dict = torch.load(model_path, map_location=lambda storage, loc: storage)['net_dict']
  File "D:\Develop\python\Anaconda3\envs\Pychramproject2\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Develop\python\Anaconda3\envs\Pychramproject2\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Develop\python\Anaconda3\envs\Pychramproject2\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort/deep_sort/deep/checkpoint/ckpt.t7'

进程已结束，退出代码为 1

**Comment by EchoYGemini** [comment]
Traceback (most recent call last):
  File "D:/pythonProject3/yolox-deepsort-main/demo.py", line 1, in <module>
    from AIDetector_pytorch import Detector
  File "D:\pythonProject3\yolox-deepsort-main\AIDetector_pytorch.py", line 6, in <module>
    from BaseDetector import baseDet
  File "D:\pythonProject3\yolox-deepsort-main\BaseDetector.py", line 1, in <module>
    from tracker import update_tracker
  File "D:\pythonProject3\yolox-deepsort-main\tracker.py", line 9, in <module>
    deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
  File "D:\pythonProject3\yolox-deepsort-main\deep_sort\deep_sort\deep_sort.py", line 19, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "D:\pythonProject3\yolox-deepsort-main\deep_sort\deep_sort\deep\feature_extractor.py", line 13, in __init__
    state_dict = torch.load(model_path, map_location=lambda storage, loc: storage)['net_dict']
  File "D:\Develop\python\Anaconda3\envs\Pychramproject2\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Develop\python\Anaconda3\envs\Pychramproject2\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Develop\python\Anaconda3\envs\Pychramproject2\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort/deep_sort/deep/checkpoint/ckpt.t7'

进程已结束，退出代码为 1

**Comment by EchoYGemini** [comment]
在[百度云(密码：fbuw)](https://pan.baidu.com/s/1YJ1iPpdFTlUyLFoonYvozg#list/path=/)中下载ckpt.t7，放入deep_sort/deep/checkpoint/目录下
